// Four variants of the loadable register from Task 3, each with exactly one bug.
// Do not edit this file -- diagnose each bug, then write corrected versions in
// fixed_regs.v. All four are structured the same way: a combinational block
// computes next_q, and a sequential block registers next_q into q on posedge clk.

module reg_bug1 (
    input wire clk,
    input wire rst,
    input wire load,
    input wire d,
    output reg q
);
    reg next_q;

    always @(load) begin
        if (load)
            next_q = d;
        else
            next_q = q;
    end

    always @(posedge clk) begin
        if (rst)
            q <= 1'b0;
        else
            q <= next_q;
    end
endmodule

module reg_bug2 (
    input wire clk,
    input wire rst,
    input wire load,
    input wire d,
    output reg q
);
    reg next_q;

    always @(*) begin
        if (load)
            next_q = d;
    end

    always @(posedge clk) begin
        if (rst)
            q <= 1'b0;
        else
            q <= next_q;
    end
endmodule

module reg_bug3 (
    input wire clk,
    input wire rst,
    input wire load,
    input wire d,
    output reg q
);
    wire next_q;

    assign next_q = load ? d : q;

    always @(posedge clk) begin
        if (rst)
            q = 1'b0;
        else
            q = next_q;
    end
endmodule

module reg_bug4 (
    input wire clk,
    input wire rst,
    input wire load,
    input wire d,
    output reg q
);
    always @(posedge clk) begin
        if (load)
            q <= d;
    end

    always @(posedge clk) begin
        if (rst)
            q <= 1'b0;
    end
endmodule
